/**
 * Dados mock estáticos para o PetFinder.
 * Extraídos dos designs SVG do Figma.
 */

export const MOCK_LOST_PETS = [
  {
    id: '1',
    name: 'Rex',
    species: 'Cachorro',
    breed: 'Golden Retriever',
    sex: 'Macho',
    size: 'Grande',
    color: 'Dourado',
    status: 'perdido',
    location: 'Marco, Belém - PA',
    description: 'Mancha branca no olho esquerdo. Responde por Rex.',
    missingDate: '05/06/2026',
    photo: null,
    owner: 'João Silva',
  },
  {
    id: '2',
    name: 'Thor',
    species: 'Cachorro',
    breed: 'Vira-lata',
    sex: 'Macho',
    size: 'Médio',
    color: 'Caramelo',
    status: 'perdido',
    location: 'Pedreira, Belém - PA',
    description: 'Usa coleira azul com plaquinha. Muito dócil.',
    missingDate: '20/05/2026',
    photo: null,
    owner: 'Ana Costa',
  },
  {
    id: '3',
    name: 'Mimi',
    species: 'Gato',
    breed: 'Siamês',
    sex: 'Fêmea',
    size: 'Pequeno',
    color: 'Bege e Marrom',
    status: 'perdido',
    location: 'Nazaré, Belém - PA',
    description: 'Gata tímida, olhos azuis. Foge quando assustada.',
    missingDate: '01/06/2026',
    photo: null,
    owner: 'Carlos Ferreira',
  },
  {
    id: '4',
    name: 'Bob',
    species: 'Cachorro',
    breed: 'Cocker Spaniel',
    sex: 'Macho',
    size: 'Médio',
    color: 'Dourado',
    status: 'perdido',
    location: 'Umarizal, Belém - PA',
    description: 'Muito brincalhão, orelhas longas.',
    missingDate: '15/05/2026',
    photo: null,
    owner: 'Julia Ribeiro',
  },
];

export const MOCK_FOUND_PETS = [
  {
    id: '10',
    name: 'Desconhecido',
    species: 'Cachorro',
    breed: 'Labrador',
    sex: 'Macho',
    size: 'Grande',
    color: 'Preto',
    status: 'encontrado',
    location: 'Batista Campos, Belém - PA',
    description: 'Encontrado sem coleira. Parece bem cuidado.',
    foundDate: '08/06/2026',
    photo: null,
    finder: 'Maria Santos',
  },
  {
    id: '11',
    name: 'Desconhecido',
    species: 'Gato',
    breed: 'Rajado',
    sex: 'Macho',
    size: 'Pequeno',
    color: 'Cinza e Preto',
    status: 'encontrado',
    location: 'Cremação, Belém - PA',
    description: 'Gato magro, parece perdido há alguns dias.',
    foundDate: '09/06/2026',
    photo: null,
    finder: 'Pedro Lima',
  },
];

export const MOCK_ADOPTION_PETS = [
  {
    id: '20',
    name: 'Luna',
    species: 'Cachorro',
    breed: 'Vira-lata',
    sex: 'Fêmea',
    size: 'Médio',
    color: 'Caramelo',
    status: 'adocao',
    location: 'Pedreira, Belém',
    age: '2 anos',
    tags: ['Vacinada'],
    favorited: true,
    photo: null,
  },
  {
    id: '21',
    name: 'Pipoca',
    species: 'Gato',
    breed: 'Gato Rajado',
    sex: 'Macho',
    size: 'Pequeno',
    color: 'Rajado',
    status: 'adocao',
    location: 'Nazaré, Belém',
    age: '1 ano',
    tags: ['Castrado'],
    favorited: false,
    photo: null,
  },
  {
    id: '22',
    name: 'Bolt',
    species: 'Cachorro',
    breed: 'Pinscher',
    sex: 'Macho',
    size: 'Pequeno',
    color: 'Preto e Marrom',
    status: 'adocao',
    location: 'Umarizal, Belém - PA',
    age: '3 anos',
    tags: ['Dócil', 'Vacinado'],
    favorited: false,
    photo: null,
  },
  {
    id: '23',
    name: 'Mel',
    species: 'Gato',
    breed: 'Gata Persa',
    sex: 'Fêmea',
    size: 'Médio',
    color: 'Branco',
    status: 'adocao',
    location: 'Marco, Belém - PA',
    age: '4 anos',
    tags: ['Castrada'],
    favorited: false,
    photo: null,
  },
];

export const MOCK_SEARCH_RESULTS = [
  {
    id: '1',
    name: 'Rex',
    breed: 'Golden Retriever',
    size: 'Grande',
    location: 'Marco, Belém - PA',
    missingDate: '05/06/2026',
    similarity: 87,
    photo: null,
  },
  {
    id: '30',
    name: 'Buddy',
    breed: 'Labrador',
    size: 'Grande',
    location: 'Nazaré, Belém - PA',
    missingDate: '28/05/2026',
    similarity: 72,
    photo: null,
  },
  {
    id: '4',
    name: 'Thor',
    breed: 'Vira-lata',
    size: 'Médio',
    location: 'Pedreira, Belém - PA',
    missingDate: '20/05/2026',
    similarity: 54,
    photo: null,
  },
  {
    id: '5',
    name: 'Bob',
    breed: 'Cocker Spaniel',
    size: 'Médio',
    location: 'Umarizal, Belém - PA',
    missingDate: '15/05/2026',
    similarity: 41,
    photo: null,
  },
  {
    id: '31',
    name: 'Mel',
    breed: 'Poodle',
    size: 'Pequeno',
    location: 'Sacramenta, Belém - PA',
    missingDate: '10/05/2026',
    similarity: 28,
    photo: null,
  },
];

export const MOCK_CHATS = [
  {
    id: 'c1',
    name: 'Maria Santos',
    initials: 'MS',
    initialsColor: '#EE791C',
    lastMessage: 'Vi um cachorro parecido com o Rex...',
    time: '10:32',
    unread: 2,
  },
  {
    id: 'c2',
    name: 'Pedro Lima',
    initials: 'PL',
    initialsColor: '#455A64',
    lastMessage: 'Olá! O gato que você encontrou é...',
    time: '09:15',
    unread: 1,
  },
  {
    id: 'c3',
    name: 'Ana Costa',
    initials: 'AC',
    initialsColor: '#EE791C',
    lastMessage: 'Obrigada pela ajuda! Já encontrei.',
    time: 'Ontem',
    unread: 0,
  },
  {
    id: 'c4',
    name: 'Carlos Ferreira',
    initials: 'CF',
    initialsColor: '#455A64',
    lastMessage: 'Pode enviar mais fotos?',
    time: 'Seg',
    unread: 0,
  },
  {
    id: 'c5',
    name: 'Julia Ribeiro',
    initials: 'JR',
    initialsColor: '#EE791C',
    lastMessage: 'Boa tarde! Sobre o Labrador...',
    time: '12/06',
    unread: 0,
  },
];

export const MOCK_NOTIFICATIONS = [
  {
    id: 'n1',
    type: 'match',
    title: 'Match encontrado! 🎉',
    message: 'Um pet com 87% de similaridade ao Rex foi identificado na região do Marco.',
    time: '10:30',
    read: false,
    section: 'HOJE',
  },
  {
    id: 'n2',
    type: 'message',
    title: 'Nova mensagem',
    message: 'Maria Santos enviou uma mensagem sobre o Rex.',
    time: '9:45',
    read: false,
    section: 'HOJE',
  },
  {
    id: 'n3',
    type: 'success',
    title: 'Pet cadastrado com sucesso',
    message: 'O pet "Rex" foi registrado. A IA está processando os embeddings.',
    time: 'Ontem',
    read: true,
    section: 'ONTEM',
  },
  {
    id: 'n4',
    type: 'contact',
    title: 'Contato solicitado',
    message: 'Ana Costa quer contatar você sobre o pet "Mimi".',
    time: 'Ontem',
    read: true,
    section: 'ONTEM',
  },
  {
    id: 'n5',
    type: 'info',
    title: 'IA processou com sucesso',
    message: 'Embeddings do pet "Rex" gerados.',
    time: '10/06',
    read: true,
    section: 'ANTERIORES',
  },
  {
    id: 'n6',
    type: 'favorite',
    title: 'Novo favorito',
    message: 'Alguém favoritou o pet "Thor".',
    time: '08/06',
    read: true,
    section: 'ANTERIORES',
  },
];

export const MOCK_USER = {
  name: 'João Silva',
  email: 'joao.silva@email.com',
  initials: 'JS',
  petsCount: 3,
  joinDate: 'Membro desde Mai/2026',
};

export const FILTER_OPTIONS = [
  { id: 'all', label: 'Todos' },
  { id: 'dogs', label: 'Cães 🐶' },
  { id: 'cats', label: 'Gatos 🐱' },
  { id: 'puppies', label: 'Filhotes' },
];

export const SPECIES_OPTIONS = ['Cachorro', 'Gato', 'Outro'];
export const SIZE_OPTIONS = ['Pequeno', 'Médio', 'Grande'];
export const SEX_OPTIONS = ['Macho', 'Fêmea'];
